chore: Add missing rules import
Fix the following error:

$ ./namcap-devel
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/yen/tmp/namcap/namcap.py", line 160, in <module>
    modules = get_modules()
  File "/home/yen/tmp/namcap/namcap.py", line 18, in get_modules
    return Namcap.rules.all_rules
AttributeError: module 'Namcap' has no attribute 'rules'